config/routes.rb
Odcdecoration::Application.routes.draw do

    match "decoration/view" => "decorations#expense", :as => :expense
        match "decoration/data" => "decorations#data", :as => :data
                match "decoration/dbaction" => "decorations#dbaction", :as => :dbaction
  resources :roles
  resources :tasks 
  devise_for :users
  resources :users
  resources :zones
  resources :decorations do
    collection do
      get :home
      get :fetch_data
      get :expense
      get :data
      get :dbaction
    end
    resources :tasks 
   end

resources :decorations do
    collection { post :import }
  end

   root :to => 'decorations#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/decoration.rb
class Decoration < ActiveRecord::Base
	attr_accessible :name, :year, :zone_id 
	validates :name,  :presence => true,:uniqueness => true
	validates :year,  :presence => true
	validates_attachment_content_type :expense, :content_type => ['application/excel','application/vnd.ms-excel','application/
	vnd.msexcel']
	attr_accessible :expense
    has_attached_file :expense
    has_many:tasks
    has_many:decorationexpenses

end

app/models/role.rb
class Role < ActiveRecord::Base
	 has_and_belongs_to_many :users
	 attr_accessible :name 
	 validates :name,  :presence => true,:uniqueness => true
end

app/controllers/decorations_controller.rb
class DecorationsController < ApplicationController
  # GET /decorations
  # GET /decorations.json


     def import
      
if params[:file]==nil

  redirect_to expense_decorations_path(:decoration => params[:decoration]), notice: "Please select any file."
   
else
    case File.extname(params[:file].original_filename)
  when '.xls' then Decorationexpense.import(params[:file],params[:decoration])
     redirect_to expense_decorations_path(:decoration => params[:decoration]), notice: "Expense imported."

  else  redirect_to expense_decorations_path(:decoration => params[:decoration]), notice: "Invalid file extension."
  end
    end 
   
     end


    def expense
     @decoration =  Decoration.find(params[:decoration])  

    end

     def data

        @decorationexpenses = Decorationexpense.where(:decoration_id=> params[:decoration])

   
    end


    def dbaction
        #called for all db actions
                name = params["c0"]
          amount   = params["c1"]
          decoration_id            = params["c2"]

        @mode = params["!nativeeditor_status"]
        
        @id = params["gr_id"]
        case @mode
            when "inserted"
                decorationexpense = Decorationexpense.new
                decorationexpense.name = name
                decorationexpense.amount = amount
                decorationexpense.decoration_id = params[:decoration]
                decorationexpense.save!
                
                @tid = decorationexpense.id
            when "deleted"
                decorationexpense=Decorationexpense.find(@id)
                decorationexpense.destroy
                
                @tid = @id
            when "updated"
                decorationexpense=Decorationexpense.find(@id)
                decorationexpense.name = name
                decorationexpense.amount = amount
                decorationexpense.decoration_id = params[:decoration]
                decorationexpense.save!
                
                @tid = @id
        end 
    end


    def home
    @tasks=Tasks_user.where(:user_id=>current_user.id) 
        @decorations = Decoration.all
        respond_to do |format|
       format.html 
       format.js { render :layout=>false }
       
      end
    end  
 
 # def fetch_data
  #   if (params[:year]=="")
   #else
    #   @decorations=Decoration.where(:year=> params[:year])
      # render :layout => false
     #end
  #end  

  def index
   
  @decorations= Decoration.page( params[:page]).per(5).order("id asc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decorations }
    end
  end

  # GET /decorations/1
  # GET /decorations/1.json
  def show
    @decoration = Decoration.find(params[:id])
    @tasks = @decoration.tasks.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @decoration }
    end
  end

  # GET /decorations/new
  # GET /decorations/new.json
  def new
    @decoration = Decoration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @decoration }
    end
  end

  # GET /decorations/1/edit
  def edit
    @decoration = Decoration.find(params[:id])
  end

  # POST /decorations
  # POST /decorations.json
  def create
    @decoration = Decoration.new(params[:decoration])

    respond_to do |format|
      if @decoration.save
        format.html { redirect_to @decoration, notice: 'Decoration was successfully created.' }
        format.json { render json: @decoration, status: :created, location: @decoration }
      else
        format.html { render action: "new" }
        format.json { render json: @decoration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decorations/1
  # PUT /decorations/1.json
  def update
    @decoration = Decoration.find(params[:id])

    respond_to do |format|
      if @decoration.update_attributes(params[:decoration])
        format.html { redirect_to @decoration, notice: 'Decoration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @decoration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decorations/1
  # DELETE /decorations/1.json
  def destroy
    @decoration = Decoration.find(params[:id])
    @decoration.destroy

    respond_to do |format|
      format.html { redirect_to decorations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decorations_helper.rb
module DecorationsHelper
end

app/views/decorations/_expense.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">




<html>
    <head>

    </head>

    <body>
        <div id="grid_here" style="width:300px; height:400px;">
        </div>
        <script type="text/javascript" charset="utf-8">
      var deco = getUrlVars()["decoration"];

 

      var grid = new dhtmlXGridObject("grid_here");
            grid.setImagePath("");
            grid.setHeader("Name, Amount");
           
            grid.setColSorting("str,str");
            grid.setInitWidths("150,150");
            grid.setSkin("dhx_skyblue");
   grid.setColTypes("ed,ed");

            grid.init();
            grid.load("/decoration/data?decoration="+deco);
            
            dp = new dataProcessor("/decoration/dbaction?decoration="+deco);
            dp.init(grid);
alert("hi");
            
function getUrlVars() {
    var vars = {};
    var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
        vars[key] = value;
    });
    return vars;
}

        </script>
        <input type="button" value="Add" onclick="grid.addRow(grid.uid(),'new expense')">
        <input type="button" value="Delete" onclick="grid.deleteSelectedRows()">

   
   
    </body>

</html>

app/views/decorations/_form.html.erb
<center><%= form_for(@decoration) do |f| %>
  <% if @decoration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decoration.errors.count, "error") %> prohibited this decoration from being saved:</h2>

      <ul>
      <% @decoration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table id="newform">
  <tr>
  <td>
    <%= f.label "Theme name" %></td>
    <td><%= f.text_field :name %></td>

</tr>
<tr>
    <td><%= f.label :year %>
</td>
<td><%= f.select :year, [ '2007','2008','2009','2010','2011','2012','2013' ], :prompt=> 'Select Year' %>
</td></tr>
<tr><td>

    <% @zone=Zone.order('name ASC') %>
    <%= f.label :zone_id %></td>
    <td>
    <%= f.collection_select :zone_id ,@zone,:id,:name %>
  </td>
</tr>
  <tr><td>
  Expense</td>
 <td><% if @decoration.expense.exists? %>
<%=  link_to "Download", @decoration.expense.url(:original, false) %>
<% elsif @decoration.name == nil %>

<% else %>
<font color="Red"> No file uploaded for expense</font>
<% end %>


    <%= f.file_field :expense %>   </td>
  </tr>
  <tr>
  <td colspan="2" align="center">
   <center> <%= f.submit %></center>
  </td>
</table>
<% end %>

app/views/decorations/_list.html.erb

<h2>json list</h2>



<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Zone</th>
   
  </tr>

<% @decorations.each do |decoration| %>
  <tr>
    <td><%= decoration.name %></td>
    <td><%= decoration.year %></td>
    <td><%= decoration.zone_id %></td>
    
  </tr>
<% end %>
</table>

<br />



app/views/decorations/edit.html.erb
<center><br/><br/><h1>Editing decoration</h1>

<%= render 'form' %>

<%= link_to 'Show', @decoration %> |
<%= link_to 'Back', decorations_path %>

app/views/decorations/expense.html.erb



<center>
	<h1> Add Expense </h1>
<font><b>Note:</b>You can add the expense manually by clicking on the add button in the below table or import an excel sheet.<br/>
Make sure the excel file have a heading called 'name' and 'amount and the extension is .xls'</font>
<br/>
<br/>
<%= form_tag import_decorations_path(:decoration =>params[:decoration]), multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
  <% end %>
 <font color="red"> <%= notice %></font>
	<%= render 'expense' %></center>

app/views/decorations/fetch_data.html.erb
<div id="year_list">
<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Zone</th>
   
  </tr>

<% @decorations.each do |dec| %>
<% @zone=Zone.find(dec.zone_id) %>
  <tr>
    <td><%= dec.name %></td>
    <td><%= dec.year %></td>
    <td><%= @zone.name %></td>
    
  </tr>
<% end %>
</table>

app/views/decorations/home.html.erb

<br/>
<br/>

<center><h1>Your Task List</h1></center>
<table id="table_id" >
<thead> 
   <tr>
    <th>Task Name</th>
    <th>Theme Name</th>
    <th>Zone</th>
    <th>Year</th>
    <th>Assigned Users</th>
    
   
  </tr>
</thead>
<tbody>


<% @tasks.each do |t| %>
<% @task=Task.find(t.task_id) %>
<% @user=User.find(t.user_id) %>
<% @decoration=Decoration.find(@task.decoration_id) %>
<% @zone=Zone.find(@decoration.zone_id) %>
 <tr>
    <td><%= @task.name %></td>
    <td><%= @decoration.name %></td>
    <td><%= @zone.name %></td>
    <td><%= @decoration.year %></td>
    <td><%= @task.users.map(&:username).join(', ')%></td>

    
  </tr>
<%end %>
</tbody>
</table>



app/views/decorations/home.js.erb
$("#deco_list").html("<%= escape_javascript(render('list')) %>");
alert("json");

app/views/decorations/index.html.erb
<br/><br/><center>

<script type="text/javascript">

</script>
  <h1>Listing decorations</h1>
  <%= paginate @decorations %> 
<table id="table_id"> 
<thead> 
<tr>
    <th>Name</th>
    <th>Year</th>
    <th>Expense</th>
    <th>Zone</th>
       <th></th>
    <th></th>
    <th></th>
      <th></th>
       <th></th>
  </tr>
</thead> <tbody>
<% @decorations.each do |decoration| %>
<% @zone=Zone.find(decoration.zone_id) %>
 
  <tr>
    <td><%= decoration.name %></td>
    <td><%= decoration.year %></td>
    <td>
      <% if decoration.expense.exists? %>
       <%=  link_to "Download", decoration.expense.url(:original, false) %>
      <% else %>
      <font color="red"> No file uploaded for expense </font>
       <% end %>
    
    </td>
    <td><%= @zone.name %></td>
    <td><%= link_to 'Assign tasks', decoration %></td>
    <td><%= link_to 'Add expense', expense_decorations_path(:decoration => decoration.id) %></td>
    <td><%= link_to 'Show', decoration %></td>
    <td><%= link_to 'Edit', edit_decoration_path(decoration) %></td>
    <td><%= link_to 'Destroy', decoration, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Decoration', new_decoration_path %>

app/views/decorations/new.html.erb
<center><br/>
<br/><h1>New decoration</h1>

<%= render 'form' %>

<%= link_to 'Back', decorations_path %>

app/views/decorations/show.html.erb
<script type="text/javascript">
$(document).ready(function(){

    $("#users").multiselect();
});
</script>
<font color="red"><%= notice %></font>
<h3><font color="#006699"> Add tasks and users</h3></font>
<table>
  <tr>
  <td>Theme name:</td>
  <td><%= @decoration.name %></td>
</tr>
<tr>
  <td>Year:</td>
  <td><%= @decoration.year %></td>
</tr>


<%= form_for([@decoration, @decoration.tasks.build]) do |f| %>

  <tr>
    <td><%= f.label "Task " %></td>
    <td><%= f.text_field :name %></td>
  </tr>
<tr>

<td>Select Users:</td>
<td><%= select_tag("user_ids", options_for_select(User.all.collect{|u|[u.username,u.id]}),{:multiple=> true,:size =>3, :id => "users"}) %>
</td>
</tr>
  <tr>
   <td colspan="2"><center> <%= f.submit %></center></tr>
  </table>
<% end %>

<table id="table_id"> 
<thead> 
  <tr>
    <th>Task Name</th>
    <th>Assigned to users</th>
  <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @tasks.each do |t| %>
<tr>
    <td>   <%= t.name %></td>
    <td>   <% t.users.each do |user| %> '<%=user.username%>' &nbsp; <% end %></td>
     <td><%= link_to 'Edit', edit_task_path(t) %></td>
    <td><%= link_to 'Destroy', t, confirm: 'Are you sure?', method: :delete %></td>
     <% end %>
  </tr>
</tbody>
</table><br />