config/routes.rb
Odcdecoration::Application.routes.draw do

    match "decoration/view" => "decorations#expense", :as => :expense
        match "decoration/data" => "decorations#data", :as => :data
                match "decoration/dbaction" => "decorations#dbaction", :as => :dbaction
  resources :roles
  resources :tasks 
  devise_for :users
  resources :users
  resources :zones
  resources :decorations do
    collection do
      get :home
      get :fetch_data
      get :expense
      get :data
      get :dbaction
    end
    resources :tasks 
   end

resources :decorations do
    collection { post :import }
  end

   root :to => 'decorations#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	attr_accessible :name 
	validates :name,  :presence => true,:uniqueness => true
	has_many :decorations
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  # GET /zones
  # GET /zones.json

  def index
  
  @zones= Zone.page( params[:page]).per(5).order("id asc")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zones }
    end
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @zone = Zone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zone }
    end
  end

  # GET /zones/new
  # GET /zones/new.json
  def new
    @zone = Zone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zone }
    end
  end

  # GET /zones/1/edit
  def edit
    @zone = Zone.find(params[:id])
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(params[:zone])

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render json: @zone, status: :created, location: @zone }
      else
        format.html { render action: "new" }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zones/1
  # PUT /zones/1.json
  def update
    @zone = Zone.find(params[:id])

    respond_to do |format|
      if @zone.update_attributes(params[:zone])
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone = Zone.find(params[:id])
    @zone.destroy

    respond_to do |format|
      format.html { redirect_to zones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table id="newform">
  <tr>
  <td>
    <%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
  <tr><td colspan="2">
  
    <center> <%= f.submit %></center>
  </td>
</tr>
</table>
<% end %>

app/views/zones/edit.html.erb
<center><br/><br/><h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<br/><br/>
<center><h1>Listing zones</h1></center>

<table id="table_id"> 
<thead> 
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @zones.each do |zone| %>
  <tr>
    <td><%= zone.name %></td>
    <td><%= link_to 'Show', zone %></td>
    <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
    <td><%= link_to 'Destroy', zone, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody
</table>

<br />

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<center><br/><br/><h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<br/><br/><p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zone.name %>


</p>


<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>